### ISSUE TITLE
Timers on activities are deleted when copying activities

### ISSUE THREAD

**Issue by mads-bo** [aau-giraf/weekplanner-OLDUI#462] opened 2020-04-29 12:42 UTC
**Describe the bug**
When copying an activity, and any other activity has a timer, all timers are deleted.

**To Reproduce**
1. Go to a weekplan
2. Click on or create one or more activities
3. Add a timer to one or more activities
4. Copy one or more activities to any day
5. See error: all timers are now missing

**Expected behavior**
Timers should be kept intact when they have already been added. Maybe they should be copied to the new activity.

**Actual behavior**
All timers are removed when any activity is copied

**Screenshots**
Not applicable.

**Environment (please complete the following information):**
Samsung S9 (SM-G960F) running One UI 2.0 (Android 10)

**Additional context**
This is probably related to #452

**Comment by giano574** [comment] 2020-04-29 12:44
Not a new issue:
https://github.com/aau-giraf/web-api/pull/98

**Comment by soenderby** [comment] 2020-12-11 08:23
This is fixed and also a duplicate of aau-giraf/web-api#98

**Closed as completed** 2020-12-11 08:23 UTC
Labels: Type: bug, Duplicate
