### ISSUE TITLE
As a guardian I would like to be able to choose a citizen so that I can choose who I’m editing the week plan for

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#47] opened 2019-03-11 06:48 UTC
Tasks:
- [ ]     Make a screen to list all citizens
- [ ]     Make/Use a BLoC to handle the data
- [ ]     Make a widget to standardize how to show a citizen.
- [ ]     When choosing a citizen I should be routed to the "Choose weekplan" screen (see #50)

**Comment by sipman** [comment] 2019-03-11 14:45
The main tasks of this feature is:
- Make a screen to list all citizens - referer the PO prototype regarding UI.
- Make/Use a BLoC to handle the data
- Make a widget to standardize how to show a citizen.
- When choosing a citizen I should be routed to the "Choose weekplan" screen (see #50)

**Comment by Tricky12321** [comment] 2019-03-20 12:59
#87

**Comment by boginw** [comment] 2019-03-20 12:59
@Tricky12321 The issue is not closed until your PR is merged

**Comment by TobiasPalludan** [comment] 2019-04-05 07:26
Now merged.

**Closed as completed by TobiasPalludan** 2019-04-05 07:26 UTC
Labels: Priority: highest
