### ISSUE TITLE
As a citizen I would like to have text shown under my pictograms that describes what it is supposed to be so that I can learn to combine words with pictures

### ISSUE THREAD

**Issue by Tekrus** [aau-giraf/weekplanner-OLDUI#267] opened 2019-05-14 07:38 UTC
**Is your feature request related to a problem? Please describe.**
Some citizen want to have text associated with pictograms so they can learn to relate words with the pictograms. 

**Describe the solution you'd like**
When searching for a pictogram in the app they have some sort of name that is used to search the database. Example when searching for banana the pictogram with the name banana or something close to it will appear. That name should also be used as the standard text that will appear under the pictograms in the weekplan, as shown in the prototype below. 
![image](https://user-images.githubusercontent.com/55434783/78660615-afb93200-78cd-11ea-8e52-63665c6ce7fd.png)

To have the text under the pictograms should be an option for the citizen which in the settings screen can be turned on or off as shown in the picture below with the "Piktogram tekst er synlig" option.

![image](https://user-images.githubusercontent.com/55434783/78655042-b9d73280-78c5-11ea-9f88-00dc21f6acdc.png)

**Additional context**
Issue #266 is similar, but is about the guardians having the option to edit the tekst for the pictorgarms. This is not suppose to edit the standard tekst for the pictogram being edited, but only the text under the activity for that pictogram.

**Comment by joandrsn** [comment] 2020-04-08 11:03
Consider using "Title" from Pictogram table.
![image](https://user-images.githubusercontent.com/5766695/78777160-53bbdf80-7999-11ea-9292-9f2f2f9dfce5.png)

**Comment by klogeat** [comment] 2020-04-23 07:36
Når der er lange figurtekster kan de ikke altid vises på weekplan skærmen. Dette er på nuværende tidspunkt håndteret ved at indsætte '...' i enden af teksten. Skal man kunne se den fulde tekst, når man klikker ind på aktiviteten? Sådan ser en aktivitet ud i weekplan skærmen:

![image](https://user-images.githubusercontent.com/37829561/80071769-7b887700-8545-11ea-8578-a0a244f449e9.png)

Her er så hvordan det vil se ud når man klikker på aktiviteten (hvis det skal tilføjes):

![image](https://user-images.githubusercontent.com/37829561/80071948-cefac500-8545-11ea-8aee-f5ce50c62590.png)

**Comment by Lortemanden** [comment] 2020-04-23 07:46
It is not a good idea to "hide" the text. The guardians and citizen want to be able to see the whole text from the activity overview. When the text becomes too big it should instead make another line and if it's just one word, like in this case, it should split the word up with a hyphen.

The last picture looks good!

**Comment by klogeat** [comment] 2020-04-23 07:51
Vi har en dependency på at noget fra web_api ([https://github.com/aau-giraf/web-api/pull/101](https://github.com/aau-giraf/web-api/pull/101)) og api_client ([https://github.com/aau-giraf/api_client/pull/45](https://github.com/aau-giraf/api_client/pull/45)) bliver merged ind i master før vores issue kan blive løst. Vi har derfor tilføjet 2x TODO i koden, som skal fixes når dette er sket. Skal vi beholde issuet selv, eller skal vi lave et Pull Request?

**Comment by klogeat** [comment] 2020-04-23 08:17
> It is not a good idea to "hide" the text. The guardians and citizen want to be able to see the whole text from the activity overview. When the text becomes too big it should instead make another line and if it's just one word, like in this case, it should split the word up with a hyphen.

Adding multiple lines on the weekplan screen would make some cards longer than others, which screws the consistent format of the weekplan screen. Also if we open the App on a phone (rather than a tablet) there is even less room for text, which would further influence this problem. We can keep the consistency if we limit it to two lines (shown in pucture), but not if we go beyond two lines. Knowing this, should we still split the text into multiple lines?

![image](https://user-images.githubusercontent.com/37829561/80075814-8c3beb80-854b-11ea-853a-290b48b184c2.png)


> The last picture looks good!

Does this mean that the text should also be added to the showActivityScreen?

**Comment by Lortemanden** [comment] 2020-04-23 08:26
> > It is not a good idea to "hide" the text. The guardians and citizen want to be able to see the whole text from the activity overview. When the text becomes too big it should instead make another line and if it's just one word, like in this case, it should split the word up with a hyphen.
> 
> Adding multiple lines on the weekplan screen would make some cards longer than others, which screws the consistent format of the weekplan screen. Also if we open the App on a phone (rather than a tablet) there is even less room for text, which would further influence this problem. We can keep the consistency if we limit it to two lines (shown in pucture), but not if we go beyond two lines. Knowing this, should we still split the text into multiple lines?
> 
> ![image](https://user-images.githubusercontent.com/37829561/80075814-8c3beb80-854b-11ea-853a-290b48b184c2.png)
> 
> > The last picture looks good!
> 
> Does this mean that the text should also be added to the showActivityScreen?

It would be fair to say that we limit it to two lines, but if it's a single word it would be nice if it could split the word better then in the picture? Maybe with a auto hyphenation feature? 

On the different screen sizes would the size of the text not scale to the screen? So the same word will f.eks always use two lines no matter the screen size, but the size of the test might differ?

**Comment by klogeat** [comment] 2020-04-23 10:20
> It would be fair to say that we limit it to two lines, but if it's a single word it would be nice if it could split the word better then in the picture? Maybe with a auto hyphenation feature?

Flutter does not support Hyphenation yet, however, they have it as a [feature goal](https://github.com/flutter/flutter/issues/18443), meaning it might be implemented in the coming months/years. Implementing our own Hyphenation system would be very time consuming and is a bit out of scope for this issue. Should i add a new issue that adresses this problem (and can be imlpemented when flutter adds the feature)?

**Closed as completed** 2020-04-27 08:08 UTC
Labels: Priority: medium, Type: new feature

**Comment by EsbenNedergaard** [comment] 2020-04-29 06:39
The issue is not entirely done because we have added 2 ToDo's where the value of a boolean variable should be bound to the setting value, which was created in aau-giraf/web-api#101 and aau-giraf/api_client#45

However this binding could not be created before they have been merged into master. (a new issue has been created to solve these two ToDo's #433)
